### ISSUE TITLE
AddDatabase in AppHost causes crash while generating manifests

### ISSUE THREAD

**Issue by sschwarz** [prom3theu5/aspirational-manifests#138] opened 2024-03-18 10:35 UTC
### 🔥 Bug Description
When there is AddDatabase used in orchestration definition, generating manifests always crash without any error message. AddDatabase is necessary for propagation of Connection string to the service, so there is no good workaround - can be deployed only with external database service connected through hardcoded secrets.

### 🔍 Steps to Reproduce the Bug
1. just add some database container (we are using postgres) and connect it to service using AddDatabase - see https://learn.microsoft.com/en-us/dotnet/aspire/database/postgresql-component?tabs=dotnet-cli

Problem is already mentioned in bug #137, but only in correlation with docker-compose export. Looks like same problem is independent on output type and there is no workaround.

**Comment by mohdali** [comment] 2024-03-23 15:20
I can confirm the same issue. If you edit the manifest to replace the database value with the connection string from the container, then you are able to peoceed. So the issue is dealing with value types.

**Comment by luuk777w** [comment] 2024-04-02 10:29
Also facing the same issue. After trying the fixes proposed in #141, I can confirm this fixes the issue.

**Comment by SaMaxNet** [comment] 2024-04-03 09:12
Same issue here with sqlserver. #141 fixes the issue that generating manifest crashes. But doesnt fix the issue that the output is useable.
Im trying to use the "aspirate generate --output-format compose" command. This generates the docker file then but leaves placeholders for the connectionstring and doesnt add a container for the db server

**Comment by prom3theu5** [comment] 2024-04-09 17:58
Thanks - going to look at this tomorrow. Been on annual Vacation 

@SaMaxNet would it be possible for you to provider a sample AppHost setup that you encounter the issue on?
Thanks

**Comment by prom3theu5** [comment] 2024-04-11 09:40
This should be fixed by the changes for Aspire preview 5 in release 0.5.0-preview.

**Closed by prom3theu5** 2024-04-11 09:40 UTC
